<script src="{{ asset('js/tip.js') }}" defer></script><div class="unbd2"><p>
<br><a href="/home/user" id="but1">Torna indietro</a><br><br><br>
<table>

<tr><td>Codice prodotto</td><td>Codice categoria</td><td>Nome</td><td>Descrizione</td><td>Prezzo</td><td>Stock</td><td>Negozio</td><td>Modifica stock</td><td>Elimina</td><td>Home</td><td>Nascondi</td></tr>
@foreach ($q1 as $q3)
    <tr><td>{{$q3->codice}}</td><td>{{$q3->codice_rep }}</td><td>{{$q3->nome}}</td><td>{{$q3->descrizione}}</td><td>{{$q3->prezzo}}</td><td>{{$q3->stock}}</td><td>{{$q3->codice_m}}</td><td><form style='margin-block-end: 0em;'action='/home/admin/item/update' method='POST'><input type="hidden" name="_token" value="{{ csrf_token() }}"><div style='flex-direction:row; justify-content: space-between;'class='flex1'><input type='hidden' name='update-num' value='{{$q3->codice}}'><input name='update-stock' class='input-box' style='width: 60px; height: 30px;'></input><button style='padding: 2px 13px;' id='but1'>+</button></div></form></td><td><form style='margin-block-end: 0em;' class='elimina' action='/home/admin/item/update' method='POST'><input type="hidden" name="_token" value="{{ csrf_token() }}"><div style='flex-direction:row; justify-content: space-between;'class='flex1'><input class='delete-item' type='hidden' name='delete-item' value='{{$q3->codice}}'><button style='padding: 3px 15px;' id='but1'>x</button></div></form></td><td><form style='margin-block-end: 0em;'action='/home/admin/item/update' method='POST'><input type="hidden" name="_token" value="{{ csrf_token() }}"><div style='flex-direction:row; justify-content: space-between;'class='flex1'><input type='hidden' name='update-home' value='{{ $q3->codice}}'>    @if (Item::showHome($q3->codice) == '1' ) <img src='/img/ok.png' style='height: 20px; margin-right: 5px;'>@else <img src='/img/no.png' style='height: 30px;'>@endif<button style='padding: 2px 13px;' id='but1'>o</button></div></form></td><td><form style='margin-block-end: 0em;'action='/home/admin/item/update' method='POST'><input type="hidden" name="_token" value="{{ csrf_token() }}"><div style='flex-direction:row; justify-content: space-between;'class='flex1'><input type='hidden' name='update-hidden' value='{{$q3->codice}}'>@if ( Item::showHidden( $q3->codice) == '1') <img src='/img/ok.png' style='height: 20px; margin-right: 5px;'>@else <img src='/img/no.png' style='height: 30px;'>@endif<button style='padding: 2px 13px;' id='but1'>o</button></div></form></td></tr>
@endforeach
</table>
</p>
</div>